DROP TABLE SH_USERINFO;

CREATE TABLE SH_USERINFO(
  USERID NUMBER(20) PRIMARY KEY,
  NAME VARCHAR2(10) NOT NULL,
  SEX NUMBER(1) NOT NULL,
  AGE NUMBER(3) NOT NULL,
  REGTIME DATE NOT NULL
);
COMMENT ON TABLE SH_USERINFO IS '日志记录表';
COMMENT ON COLUMN SH_USERINFO.USERID     IS '用户ID';
COMMENT ON COLUMN SH_USERINFO.NAME      IS '用户名';
COMMENT ON COLUMN SH_USERINFO.SEX         IS '性别';
COMMENT ON COLUMN SH_USERINFO.AGE    IS '年龄';
COMMENT ON COLUMN SH_USERINFO.REGTIME   IS '注册时间';

DROP SEQUENCE SH_USERINFO_USERID_SEQ;
CREATE SEQUENCE SH_USERINFO_USERID_SEQ --序列名称
INCREMENT BY 1 -- 每次加几个
START WITH 1  -- 从1开始计数        
NOMAXVALUE      --NOMAXVALUE -- 不设置最大值      
ORDER                 
NOCYCLE          -- 一直累加，不循环    
CACHE 10;
CREATE OR REPLACE TRIGGER SH_USERINFO_INSERT_TG
BEFORE INSERT ON SH_USERINFO
FOR EACH ROW
BEGIN
  SELECT SH_USERINFO_USERID_SEQ.NEXTVAL INTO :NEW.USERID FROM DUAL;
END SH_USERINFO_INSERT_TG;
/